In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Flatten,MaxPool2D,Dropout
from tensorflow.keras.utils import to_categorical

In [2]:
df=pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_test_label= pd.read_csv('sample_submission_redesigned.csv')

In [3]:
df.shape

(42000, 785)

In [4]:
df_test.shape

(28000, 784)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [6]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 28000 entries, 0 to 27999
Columns: 784 entries, pixel0 to pixel783
dtypes: int64(784)
memory usage: 167.5 MB

In [7]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X_train = df.drop("label", axis=1).values
y_train = df["label"].values
X_test = df_test.values
y_test = df_test_label['Label'].values

In [10]:
df_test_label['Label'].value_counts()

Label
1    3289
4    3003
7    2903
8    2777
3    2756
0    2740
6    2684
2    2651
9    2610
5    2587
Name: count, dtype: int64

In [11]:
X_train = X_train/255.0
X_test = X_test/255.0

In [12]:
x_train_resape = X_train.reshape(-1,28,28)
x_test_resape = X_test.reshape(-1,28,28)

In [13]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(42000, 784))

In [14]:
x_train_resape.shape

(42000, 28, 28)

In [15]:
y_train_cat = to_categorical(y_train,10)
y_test_cat = to_categorical(y_test,10)

In [16]:
y_train_cat

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(42000, 10))

In [17]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation='softmax')
])

In [18]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
history_per = model.fit(x_train_resape,y_train_cat,
            epochs=20,batch_size=32,
            validation_data=(x_test_resape,y_test_cat),verbose=1)

Epoch 1/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8627 - loss: 0.5289 - val_accuracy: 0.9429 - val_loss: 0.2341
Epoch 2/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9111 - loss: 0.3161 - val_accuracy: 0.9507 - val_loss: 0.1871
Epoch 3/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9186 - loss: 0.2884 - val_accuracy: 0.9529 - val_loss: 0.1702
Epoch 4/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9224 - loss: 0.2747 - val_accuracy: 0.9540 - val_loss: 0.1615
Epoch 5/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9249 - loss: 0.2659 - val_accuracy: 0.9550 - val_loss: 0.1564
Epoch 6/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9261 - loss: 0.2596 - val_accuracy: 0.9554 - val_loss: 0.1531
Epoch 7/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9272 - loss: 0.2547 - val_accuracy: 0.9562 - val_loss: 0.1508
Epoch 8/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9290 - loss: 0.2508 - val_accuracy: 0.9561 - val_loss: 0.1493
Epoch 9/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9299 - loss: 0.2475 - val_accuracy: 0.9561 - val_loss: 0.1481
Epoch 10/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9308 - loss: 0.2446 - val_accuracy: 0.9559 - val_loss: 0.1473
Epoch 11/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9315 - loss: 0.2422 - val_accuracy: 0.9554 - val_loss: 0.1467
Epoch 12/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9320 - loss: 0.2400 - val_accuracy: 0.9553 - val_loss: 0.1463
Epoch 13/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9330 - loss: 0.2381 - val_accuracy: 0.9552 - val_loss: 0.1460
Epoch 14/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9336 - loss: 0.2363 - val_accuracy: 0.9549 - val_loss: 0.1459
Epoch 15/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9341 - loss: 0.2347 - val_accuracy: 0.9547 - val_loss: 0.1458
Epoch 16/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9346 - loss: 0.2333 - val_accuracy: 0.9547 - val_loss: 0.1458
Epoch 17/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9348 - loss: 0.2319 - val_accuracy: 0.9545 - val_loss: 0.1459
Epoch 18/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9352 - loss: 0.2307 - val_accuracy: 0.9546 - val_loss: 0.1460
Epoch 19/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9357 - loss: 0.2295 - val_accuracy: 0.9544 - val_loss: 0.1461
Epoch 20/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9361 - loss: 0.2285 - val_accuracy: 0.9542 - val_loss: 0.1463