In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Flatten,Dropout
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.utils import to_categorical

In [2]:
df=pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_test_label= pd.read_csv('sample_submission_redesigned.csv')

In [3]:
df.shape

(42000, 785)

In [4]:
df_test.shape

(28000, 784)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [6]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 28000 entries, 0 to 27999
Columns: 784 entries, pixel0 to pixel783
dtypes: int64(784)
memory usage: 167.5 MB

In [7]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X_train = df.drop("label", axis=1).values
y_train = df["label"].values
X_test = df_test.values
y_test = df_test_label['Label'].values

In [10]:
df_test_label['Label'].value_counts()

Label
1    3289
4    3003
7    2903
8    2777
3    2756
0    2740
6    2684
2    2651
9    2610
5    2587
Name: count, dtype: int64

In [11]:
X_train = X_train/255.0
X_test = X_test/255.0

In [12]:
x_train_resape = X_train.reshape(-1,28,28)
x_test_resape = X_test.reshape(-1,28,28)

In [13]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(42000, 784))

In [14]:
x_train_resape.shape

(42000, 28, 28)

In [15]:
y_train_cat = to_categorical(y_train,10)
y_test_cat = to_categorical(y_test,10)

In [16]:
y_train_cat

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(42000, 10))

In [17]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation='softmax')
])

In [18]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
history_per = model.fit(x_train_resape,y_train_cat,
            epochs=20,batch_size=32,
            validation_data=(x_test_resape,y_test_cat),verbose=1)

Epoch 1/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8668 - loss: 0.5202 - val_accuracy: 0.9437 - val_loss: 0.2320
Epoch 2/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9117 - loss: 0.3145 - val_accuracy: 0.9512 - val_loss: 0.1866
Epoch 3/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9190 - loss: 0.2876 - val_accuracy: 0.9537 - val_loss: 0.1701
Epoch 4/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9232 - loss: 0.2742 - val_accuracy: 0.9541 - val_loss: 0.1616
Epoch 5/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9251 - loss: 0.2656 - val_accuracy: 0.9548 - val_loss: 0.1566
Epoch 6/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9267 - loss: 0.2593 - val_accuracy: 0.9554 - val_loss: 0.1533
Epoch 7/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9278 - loss: 0.2545 - val_accuracy: 0.9557 - val_loss: 0.1511
Epoch 8/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9296 - loss: 0.2506 - val_accuracy: 0.9559 - val_loss: 0.1495
Epoch 9/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9305 - loss: 0.2473 - val_accuracy: 0.9559 - val_loss: 0.1484
Epoch 10/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9310 - loss: 0.2445 - val_accuracy: 0.9559 - val_loss: 0.1475
Epoch 11/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9318 - loss: 0.2420 - val_accuracy: 0.9559 - val_loss: 0.1470
Epoch 12/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9325 - loss: 0.2399 - val_accuracy: 0.9557 - val_loss: 0.1465
Epoch 13/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9333 - loss: 0.2379 - val_accuracy: 0.9557 - val_loss: 0.1463
Epoch 14/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9340 - loss: 0.2362 - val_accuracy: 0.9551 - val_loss: 0.1461
Epoch 15/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9345 - loss: 0.2346 - val_accuracy: 0.9549 - val_loss: 0.1460
Epoch 16/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9348 - loss: 0.2332 - val_accuracy: 0.9549 - val_loss: 0.1460
Epoch 17/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9351 - loss: 0.2318 - val_accuracy: 0.9546 - val_loss: 0.1461
Epoch 18/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9353 - loss: 0.2306 - val_accuracy: 0.9542 - val_loss: 0.1462
Epoch 19/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9356 - loss: 0.2295 - val_accuracy: 0.9541 - val_loss: 0.1463
Epoch 20/20
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9361 - loss: 0.2284 - val_accuracy: 0.9540 - val_loss: 0.1465

In [30]:
acc_perceptron = model.evaluate(x_test_resape,y_test_cat,verbose=1)[1]

875/875 ━━━━━━━━━━━━━━━━━━━━ 1s 659us/step - accuracy: 0.9540 - loss: 0.1465

In [23]:
acc_perceptron

0.9539999961853027

# **ANN**

In [32]:
#ANN
ann_model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(10,activation='softmax')
])

In [33]:
ann_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
# history_ann = ann_model.fit(x_train_resape,y_train_cat,epochs=10,batch_size=32,
#                             validation_data=(x_test_resape,y_test_cat),verbose=1)

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9209 - loss: 0.2670 - val_accuracy: 0.9280 - val_loss: 0.2421
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9662 - loss: 0.1097 - val_accuracy: 0.9205 - val_loss: 0.3309
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9775 - loss: 0.0732 - val_accuracy: 0.9165 - val_loss: 0.4174
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9835 - loss: 0.0525 - val_accuracy: 0.9162 - val_loss: 0.4810
Epoch 5/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9882 - loss: 0.0383 - val_accuracy: 0.9117 - val_loss: 0.5776
Epoch 6/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9896 - loss: 0.0315 - val_accuracy: 0.9122 - val_loss: 0.6441
Epoch 7/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9907 - loss: 0.0274 - val_accuracy: 0.9122 - val_loss: 0.6636
Epoch 8/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9924 - loss: 0.0234 - val_accuracy: 0.9111 - val_loss: 0.7770
Epoch 9/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9930 - loss: 0.0203 - val_accuracy: 0.9121 - val_loss: 0.8146
Epoch 10/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9935 - loss: 0.0190 - val_accuracy: 0.9114 - val_loss: 0.8583

In [37]:
history_ann = ann_model.fit(
    x_train_resape,
    y_train_cat,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9923 - loss: 0.0232 - val_accuracy: 0.9918 - val_loss: 0.0236
Epoch 2/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9946 - loss: 0.0174 - val_accuracy: 0.9906 - val_loss: 0.0257
Epoch 3/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9956 - loss: 0.0128 - val_accuracy: 0.9926 - val_loss: 0.0239
Epoch 4/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9970 - loss: 0.0095 - val_accuracy: 0.9898 - val_loss: 0.0347
Epoch 5/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9971 - loss: 0.0088 - val_accuracy: 0.9906 - val_loss: 0.0306
Epoch 6/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9945 - loss: 0.0161 - val_accuracy: 0.9889 - val_loss: 0.0350
Epoch 7/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9975 - loss: 0.0076 - val_accuracy: 0.9896 - val_loss: 0.0343
Epoch 8/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9975 - loss: 0.0081 - val_accuracy: 0.9889 - val_loss: 0.0373
Epoch 9/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9953 - loss: 0.0144 - val_accuracy: 0.9874 - val_loss: 0.0467
Epoch 10/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9972 - loss: 0.0080 - val_accuracy: 0.9879 - val_loss: 0.0455

In [38]:
ann_model.evaluate(x_test_resape, y_test_cat)

875/875 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.9118 - loss: 1.1481

[1.148080825805664, 0.9118214249610901]

In [39]:
history_ann.history

{'accuracy': [0.9922916889190674,
  0.9945535659790039,
  0.9955952167510986,
  0.9969940185546875,
  0.9971428513526917,
  0.9944642782211304,
  0.9974702596664429,
  0.9975297451019287,
  0.9952678680419922,
  0.9972321391105652],
 'loss': [0.023237118497490883,
  0.017448948696255684,
  0.01281123049557209,
  0.009538748301565647,
  0.008841910399496555,
  0.016071565449237823,
  0.007562099490314722,
  0.008146585896611214,
  0.014397461898624897,
  0.008025694638490677],
 'val_accuracy': [0.9917857050895691,
  0.9905952215194702,
  0.9926190376281738,
  0.9897618889808655,
  0.9905952215194702,
  0.9889285564422607,
  0.989642858505249,
  0.9889285564422607,
  0.9873809814453125,
  0.9878571629524231],
 'val_loss': [0.02356855385005474,
  0.02567293867468834,
  0.023890379816293716,
  0.03468982130289078,
  0.030573632568120956,
  0.03501518815755844,
  0.03428642824292183,
  0.03732970356941223,
  0.046652477234601974,
  0.045513004064559937]}

# **CNN**

In [40]:
x_train_cnn = X_train.reshape(-1,28,28,1)
x_test_cnn = X_test.reshape(-1,28,28,1)

In [44]:
cnn_model = Sequential([
    Conv2D(32, kernel_size=(3,3), activation="relu", input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64, kernel_size=(3,3), activation="relu"),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),
    Dense(10, activation="softmax")
])

In [45]:
cnn_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [46]:
history_cnn = cnn_model.fit(x_train_cnn,y_train_cat,epochs=10,batch_size=32,
                            validation_data=(x_test_cnn,y_test_cat),verbose=1)

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9273 - loss: 0.2384 - val_accuracy: 0.9149 - val_loss: 0.5062
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9731 - loss: 0.0904 - val_accuracy: 0.9130 - val_loss: 0.6118
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9810 - loss: 0.0620 - val_accuracy: 0.9122 - val_loss: 0.6972
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9846 - loss: 0.0508 - val_accuracy: 0.9118 - val_loss: 0.7867
Epoch 5/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - accuracy: 0.9865 - loss: 0.0428 - val_accuracy: 0.9115 - val_loss: 0.8071
Epoch 6/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.9892 - loss: 0.0346 - val_accuracy: 0.9108 - val_loss: 0.9241
Epoch 7/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9900 - loss: 0.0308 - val_accuracy: 0.9111 - val_loss: 0.9773
Epoch 8/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9918 - loss: 0.0274 - val_accuracy: 0.9107 - val_loss: 1.0881
Epoch 9/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9922 - loss: 0.0232 - val_accuracy: 0.9107 - val_loss: 1.2135
Epoch 10/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9925 - loss: 0.0232 - val_accuracy: 0.9105 - val_loss: 1.2826